name = input("โปรดกรอกชื่อ :\n")
age = input("โปรดกรอกอายุ :\n")
number =input("โปรดกรอกรหัสระจำตัวนักเรียน :\n")
year =input("โปรดชั้นปี \n" )
nickname =input("โปรดกรอกชื่อเล่น \n:")
height =float(input("โปรดกรอกส่วนสูง :\n"))
weight =float(input("โปรดกรอกน้ำหนัก :\n"))
a = height + weight

print("ประวัติโดยย่อ")
print("ชื่อ : "+ name+ "อายุ :" + age+ "ปี")
print("รหัสประจำตัวนักเรียน :" + number+ "ระดับชั้น : " + year)
print("ชื่อเล่น : " + nickname)
print("ส่วนสูง : " + str(height) +"เซนติเมตร " + "น้ำหนัก :"  + str(weight)+ " กิโลกรัม")
print("ส่วนสูง + น้ำหนัก = " + str(a))